spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///lagou?userUnicode=true&characterEncoding=utf8
    username: root
    password: root
xiang:
  message: hello SpringCloud I'm Array You are best
  name: Hello
